# Generated by Django 4.1.4 on 2023-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Лекции', 'verbose_name_plural': 'Лекции'},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.FileField(upload_to='uploads_Lecture/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован\\Неопубликован'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
