# Generated by Django 4.1.4 on 2023-01-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content_laboratory',
            field=models.FileField(null=True, upload_to='uploads_Laboratory/%Y/%m/%d/', verbose_name='Файлы лабораторных работ'),
        ),
    ]
